apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  labels:
    name: appc-service1
  name: appc-service1
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: appc-service1-kubeconfig
      namespace: crossplane-system
    source: Secret
