apiVersion: helm.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    name: appc-service
  name: appc-service
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: appc-service-kubeconfig
      namespace: crossplane-system
    source: Secret
