apiVersion: syn.tools/v1alpha1
kind: RedisInstance
metadata:
  name: redis1
  labels:
    service.syn.tools/cluster: appc-service1
    service.syn.tools/plan: small
spec:
  compositionRef:
    name: redis-small
